FROM node:16
ENV HTTPS_PROXY ENV HTTPS_PROXY http://192.168.2.7:3128
http://192.168.2.7:3128
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
RUN npm install

EXPOSE 3000 
CMD [ "/root/A2SR/Course_1/app/node", "/root/A2SR/Course_1/app/src/index.js" ]
